### ISSUE TITLE
About the 'vb_lst' for vinfo_files for validation

### ISSUE THREAD

**Issue by Versocial** [TheShadow29/VidSitu#27]
in data/README.MD：
```
vinfo_files/:
...
For Validation file, the following keys are additionally present:

vb_to_use: The verbs used to gather Semantic Roles and Event Relations.
vb_lst: A Dictionary with keys Ev1-Ev5 and values as a list of 10-verbs
vbid_lst: Same as above, but instead of verb names, uses the verb ids.
```

I know the 'vb_lst' is the candidates for 'vb_to_use',
but  what is the 'vb_lst' used for ?
Or is there a 'vb_lst' for the Training data too ? Maybe the candidates can be used when training for verb prediction.

**Comment by TheShadow29** [comment]
@Versocial Sorry for the later reply. 

The vb_lst is because the validation datasets have 10 verbs for each event. During training, we ask the annotator to directly produce a verb+srl+event relation. 

For validation, we ask 10 annotators only the verb followed by top-consensus verb to have 3 SRL annotations.

**Comment by Versocial** [comment]
Quite Clear. Thanks for your answering . I'll close this issue.
